### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by doowb** [doowb/sort-prompt#1]
![image](https://cloud.githubusercontent.com/assets/995160/11916001/dffefd1a-a68f-11e5-8ca6-e70ec8134d76.png)

**Comment by jonschlinkert** [comment]
you should do an animated gif!

**Comment by doowb** [comment]
:santa: Great idea! I had software where I could record the command line and it would show on screen the keys I was typing. I'll see if I can use that to make it more obvious how to do the sorting.
